// app/cutout/index.tsx
import type { JSXElement } from "solid-js";
import { createSignal, Index } from "solid-js";
import styles from "./Cutout.module.css";
import type { Data } from "../chart";
import { format } from "d3-format";
import type { CutoutIndex } from "lib/CutoutIndex";
import LineChart from "../chart/LineChart";
import { bisectDate } from "../report";

interface Props {
    cutout: CutoutIndex[];
}

const formatNumber = format(".2f");

const series = (cutout: CutoutIndex[]): Data[][] => [
    cutout.map(record => ({ date: record.date, value: record.indexPrice })),
    cutout.map(record => ({ date: record.date, value: record.carcassPrice }))
];

const labels = ["Cutout", "Index"];

function Cutout(props: Props): JSXElement {
    const data = series(props.cutout);
    const [stats, setStats] = createSignal<Data[]>(data.map(series => series[series.length - 1]).reverse());

    const updateStats = ({ detail }: CustomEvent<Date>): Data[] =>
        setStats(data.map(series => series[bisectDate(series, detail)]).reverse());

    return <div on:selectDate={updateStats} class={styles.cutout}>
        <div class={styles.stats}>
            <Index each={stats()}>
                { (stat, index) =>
                    <div class={styles.stat}>
                        <h5 class={styles.label}>
                            {labels[index]}
                        </h5>

                        <h3 class={styles.value}>
                            {formatNumber(stat().value)}
                        </h3>
                    </div>
                }
            </Index>
        </div>

        <LineChart
            width={640}
            height={360}
            right={48}
            bottom={48}
            left={32}
            top={32}
            data={data}
            marker={stats()[0]}
        />
    </div>;
}

export default Cutout;

// app/reports/Cutout.svelte
<script lang="ts" context="module">
    import type CutoutIndex from "lib/cutout/CutoutIndex";
    import CutoutInteractor from "lib/cutout/CutoutInteractor";
    import ObservationChart from "../ui/ObservationChart.svelte";
    import Circle from "../ui/Circle.svelte";
    import Marker from "../ui/Marker.svelte";
    import Path from "../ui/Path.svelte";
</script>

<style lang="postcss">
    @import "Cutout.css";
</style>

<script lang="ts">
    export let cutout: Iterable<CutoutIndex>;
    const model = new CutoutInteractor(cutout);
</script>

<div class="cutout report">
    <div class="stats">
        {#each $model.stats as stat}
            <div class="stat">
                <h5 class="label">{stat.label}</h5>
                <h3 class="value">{stat.value}</h3>
            </div>
        {/each}
    </div>

    <ObservationChart
        dates={$model.dates}
        values={$model.values}
        on:selectDate={event => model.selectDate(event.detail)}
        on:resetDate={model.resetDate}>

        <g class="plot" slot="plot" let:x let:y>
            <Marker x={x} y={y} point={$model.selected}/>
            <Path x={x} y={y} data={$model.cutout}/>
            <Path x={x} y={y} data={$model.index}/>
            <Circle x={x} y={y} point={$model.selected}/>
        </g>
    </ObservationChart>
</div>
