// app/reports/Cash.svelte
<script lang="ts" context="module">
    import type CashIndex from "lib/slaughter/CashIndex";
    import CashIndexInteractor from "lib/slaughter/CashIndexInteractor";
    import ObservationChart from "../ui/ObservationChart.svelte";
    import Circle from "../ui/Circle.svelte";
    import Marker from "../ui/Marker.svelte";
    import Path from "../ui/Path.svelte";
</script>

<style lang="postcss">
    @import "Cash.css";
</style>

<script lang="ts">
    export let cash: Iterable<CashIndex>;
    $: model = new CashIndexInteractor(cash);
    $: stats = model.stats;
    $: selected = model.selected;
</script>

<div class="cash report">
    <div class="stats">
        <h2 class="label">{$stats.label}</h2>
        <h2 class="value">{$stats.value}</h2>
    </div>

    <ObservationChart
        dates={model.dates}
        values={model.values}
        on:selectDate={event => model.selectDate(event.detail)}
        on:resetDate={model.resetDate}>

        <g class="plot" slot="plot" let:x let:y>
            <Marker x={x} y={y} point={$selected}/>
            <Path x={x} y={y} data={model.series} />
            <Circle x={x} y={y} point={$selected}/>
        </g>
    </ObservationChart>
</div>

// app/cash/index.tsx
import type { JSXElement } from "solid-js";
import { createSignal } from "solid-js";
import type { CashIndex } from "lib/CashIndex";
import { bisectDate, formatNumber } from "../report";
import type { Data } from "../chart";
import LineChart from "../chart/LineChart";
import styles from "./Cash.module.css";

interface Props {
    cash: CashIndex[];
}

const series = (data: CashIndex[]): Data[][] => [
    data.map(({ date, indexPrice: value }) => ({ date, value }))
];

function Cash({ cash }: Props): JSXElement {
    const [data] = series(cash);
    const [selected, setSelected] = createSignal<Data>(data[data.length - 1]);
    const getDate = (date: Date): Data => data[bisectDate(data, date)];

    return <div class={styles.cash} on:selectDate={({ detail }) => setSelected(getDate(detail))}>
        <div class={styles.stats}>
            <h2>Cash Index</h2>

            <div class={styles.stat}>
                <h2 class={styles.value}>
                    {formatNumber(selected().value)}
                </h2>
            </div>
        </div>

        <LineChart
            width={640}
            height={360}
            right={48}
            bottom={48}
            left={32}
            top={32}
            data={[data]}
            marker={selected()} />
    </div>;
}

export default Cash;
